### ISSUE TITLE
listings returns no result

### ISSUE THREAD

**Issue by huyunwei** [abresler/realtR#1]
Try to replicate the codes as I read in the Twitter, and it does not work.
```
library(realtR)
my_neighbors <- listings(locations = "Malibu, CA",
                                 beds_min = 4)
```
It gives error message:

> Unknown variables: `streetOrNeighborhoodSearch`, `zipcodeSearch`Unknown variables: `postal_code`Joining, by = "urlAPI"
> Unknown variables: `nameCity`, `stateSearch`, `zipcodeSearch`Joining, by = "item"
> Joining, by = "item"
> Unknown variables: `urlGeoAPI`, `urlAPI`

**Comment by abresler** [comment]
Do you have requestsR working?

**Comment by huyunwei** [comment]
Tried a few things as listed in http://asbcllc.com/r_packages/requestsR/introduction/index.html
requestsR seems to be working ...

**Comment by abresler** [comment]
I need more details than this but it is pretty clear that you don't have Python and requests working.  I would take a look at the reticulate documentation.  

Try reinstalling python via homebrew -- linking it -- install the requests module and then trying this again.

**Comment by huyunwei** [comment]
Here is the first few lines of the resp$content:

> b'[{"id":"7372695390","type":"PushEvent","actor":{"id":37218917,"login":"lifenghong","display_login":"lifenghong","gravatar_id":"","url":"https://api.github.com/users/lifenghong","avatar_url":"https://avatars.githubusercontent.com/u/37218917?"},"repo":{"id":124882641,"name":"lifenghong/work","url":"https://api.github.com/repos/lifenghong/work"},"payload":{"push_id":2399155768,"size":1,"distinct_size":1,"ref":"refs/heads/master","head":"68919e44afc2f5a2fdd73fa28e563e54d0b77350","before":"2dd16ade49872bd680adbea089b67e7760f2f7ac","commits":[{"sha":"68919e44afc2f5a2fdd73fa28e563e54d0b77350","author":{"email":"37218917+lifenghong@users.noreply.github.com","name":"lifenghong"},"message":"Create forth_work","distinct":true,"url":

It seems that there is an extra `b` in the beginning. after I remove that , and call the 'jsonlite::fromJSON' directly, then got error:
> Error: lexical error: invalid char in json text. 

And I can import requests in R with no problem. 

Also attached my py_config

>  reticulate::py_config()
> python:         /Users/myhome/anaconda/bin/python
> libpython:      /Users/myhome/anaconda/lib/libpython3.6m.dylib
> pythonhome:     /Users/myhome/anaconda:/Users/myhome/anaconda
> version:        3.6.4 |Anaconda custom (64-bit)| (default, Jan 16 2018, 12:04:33)  [GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
> numpy:          /Users/myhome/anaconda/lib/python3.6/site-packages/numpy
> numpy_version:  1.13.3
> requests:       /Users/myhome/anaconda/lib/python3.6/site-packages/requests
> 
> python versions found: 
>  /Users/myhome/anaconda/bin/python
>  /usr/bin/python
>  /Users/myhome/anaconda/envs/tensorflow/bin/python

Thanks ...

**Comment by abresler** [comment]
Can you please share the full code

**Comment by huyunwei** [comment]
Code is at https://github.com/huyunwei/blogdown/blob/master/content/post/2018-03-12-realtors.Rmd

Error msg already pasted in above comments. 

Thanks

**Comment by abresler** [comment]
Ok with regards to the Requests portion.  Does this work for you?  The data will be different obviously but you should end up with a data frame
<img width="583" alt="screen shot 2018-03-13 at 3 03 40 pm" src="https://user-images.githubusercontent.com/740564/37364065-d2119f42-26cf-11e8-8829-3440e31301bd.png">

**Comment by abresler** [comment]
Assuming this works reinstall the newest version of realtR and it should work

**Comment by abresler** [comment]
Was able to figure out how to use curl to eliminate the need to use requestsR download the newest version
