### ISSUE TITLE
error on install

### ISSUE THREAD

**Issue by perretti** [abresler/realtR#2]
Hi,
Sounds like a great package. But when I try to install using `devtools::install_github("abresler/realtR")`

I get the following error:

Downloading GitHub repo abresler/realtR@master
from URL https://api.github.com/repos/abresler/realtR/zipball/master
Installing realtR
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/r5/z80zbknj4dz_6pyxn_xqlfb80000gn/T/Rtmpy9OP12/devtools25412b1a4000/abresler-realtR-c802a00'  \
  --library='/Library/Frameworks/R.framework/Versions/3.4/Resources/library' --install-tests 

* installing *source* package ‘realtR’ ...
** R
** preparing package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called ‘emo’
ERROR: lazy loading failed for package ‘realtR’
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/realtR’
Installation failed: Command failed (1)

**Comment by abresler** [comment]
You need the emo package which for whatever reason isn't installing.

Try this:

```
devtools::install_github("hadley/emo")

```

Then reinstall.
