### ISSUE TITLE
Tutorial Issues Object not found and repeated filter

### ISSUE THREAD

**Issue by bhive01** [abresler/realtR#4]
Going through the tutorial here:
http://asbcllc.com/r_packages/realtR/2018/introduction/

df_alex_top <- 
####THIS OBJECT DOES NOT EXIST  
df_alex_school %>%  
#### THIS LINE IS REPEATED TWICE
  filter(scorePrediction == max(scorePrediction)) %>%
  filter(scorePrediction == max(scorePrediction)) %>% 
  select(nameLocationSearch , scorePrediction:latitudeLocation) %>%
  select(-one_of(c("idSchool", "codeCountry"))) %>%
  purrr::set_names(c(
  "search",
  "score",
  "school",
  "address",
  "city",
  "zip",
  "state",
  "lat",
  "lon"
  ))

**Comment by abresler** [comment]
This is something on the website tutorial not the actual package but I will fix it and thanks for pointing it out

**Comment by bhive01** [comment]
Yes, I tried to say this on twitter, but I wasn't clear I guess. If there is a repo for that page/website, please let me know so I can make proposals directly...

**Comment by abresler** [comment]
Haha no worries -- I got the information which is what matters!


----------------------
*Alex Bresler*
abresler@asbcllc.com

​www.asbcllc.com​

917-455-0239
​ (cell)​

@abresler <http://twitter.com/abresler> | LinkedIn
<http://www.linkedin.com/in/abresler> | My Musings <http://asbcllc.com/blog>
